
./importPtmAnnotation.pl $PORTAL_DATA_HOME/reference-data/phosphoSitePlus/Regulatory_sites phosphositeplus-regsite
./importPtmAnnotation.pl $PORTAL_DATA_HOME/reference-data/phosphoSitePlus/Disease-associated_sites phosphositeplus-disease
./importPtmAnnotation.pl $PORTAL_DATA_HOME/reference-data/phosphoSitePlus/Kinase_Substrate_Dataset phosphositeplus-kinase
./importPtmAnnotation.pl $PORTAL_DATA_HOME/reference-data/phosphoSitePlus/Phosphorylation_site_dataset phosphositeplus
./importPtmAnnotation.pl $PORTAL_DATA_HOME/reference-data/phosphoSitePlus/Acetylation_site_dataset phosphositeplus
./importPtmAnnotation.pl $PORTAL_DATA_HOME/reference-data/phosphoSitePlus/Ubiquitination_site_dataset phosphositeplus
./importPtmAnnotation.pl $PORTAL_DATA_HOME/reference-data/phosphoSitePlus/Sumoylation_site_dataset phosphositeplus
./importPtmAnnotation.pl $PORTAL_DATA_HOME/reference-data/phosphoSitePlus/O-GlcNAc_site_dataset phosphositeplus
./importPtmAnnotation.pl $PORTAL_DATA_HOME/reference-data/phosphoSitePlus/Methylation_site_dataset phosphositeplus